#!/usr/bin/env zsh

# Install native apps
brew tap caskroom/versions

brew cask install 1password
brew cask install android-file-transfer
brew cask install aerial
brew cask install atom
brew cask install bartender
brew cask install batchmod
brew cask install betterzip
brew cask install brackets
brew cask install beoplay-software-update
brew cask install calibre
brew cask install carbon-copy-cloner
brew cask install coconutbattery
brew cask install cyberduck
brew cask install daisydisk
brew cask install dropbox
brew cask install dukto
brew cask install evernote
brew cask install easyfind
brew cask install etcher
brew cask install fliqlo
brew cask install firefox
brew cask install github-desktop
brew cask install grammarly
brew cask install go2shell
brew cask install google-chrome
brew cask install google-drive
brew cask install hosts
brew cask install ifunbox
brew cask install ip-in-menu-bar
brew cask install install-disk-creator
brew cask install iterm2
brew cask install istat-menus
brew cask install logitech-unifying
brew cask install mactracker
brew cask install middleclick
brew cask install nordvpn
brew cask install numi
brew cask install osmc
brew cask install oversight
brew cask install radio-silence
brew cask install renamer
brew cask install sdformatter
brew cask install senuti
brew cask install slack
brew cask install shimo
brew cask install screenhero
brew cask install spotify
brew cask install soundflower
brew cask install teamviewer
brew cask install textwrangler
brew cask install vlc
brew cask install utorrent
brew cask install yacreader
